-- CREAZIONE TABELLA: OPERATIONS MANAGER
CREATE TABLE IF NOT EXISTS OPERATIONS_MANAGER (
    id_operations_manager INT AUTO_INCREMENT,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_operations_manager)
);
